name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches: ['main']
          
jobs:
  docker-build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ secrets.DOCKER_USERNAME }}/cpe101-viewbook:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  update-manifest:
    runs-on: ubuntu-latest
    needs: ['docker-build']
    steps:
      - uses: actions/checkout@v4
        with:
          repository: KronosMoe/kronos-helm
          ref: 'main'
          token: ${{ secrets.G_TOKEN }} 
      - name: Git config
        run: |
          git config --global user.email "mirailisclm@gmail.com"
          git config --global user.name "Mirailisc"
          echo ${{ github.sha }}
          sed -i "s#appVersion.*#appVersion: ${{ github.sha }}#g" cpe101-viewbook/Chart.yaml
          git add -A
          git commit -am "update cpe101-viewbook image to version ${{ github.sha }}" 
      - run: echo ${{ github }}
      - run: git push origin main